langauge: ruby
sudo: false
cache: bundler

branches:
  only: master

# make other rubies available for switching
before_install:
  - "ruby -e 'print(defined?(JRUBY_VERSION) ? %{jruby-#{JRUBY_VERSION}} : RUBY_VERSION)' > version"
  - rvm install 2.0.0
  - rvm install 2.1.5
  - rvm install jruby-9.1.16.0
  - rvm use $(cat version) # install switches versions, so restore

rvm:
  - 2.0
  - 2.1
  - 2.2
  - 2.3
  - 2.4
  - 2.5
  - 2.6
  - 2.7
  - jruby

matrix:
  allow_failures:
    - rvm: jruby
  fast_finish: true
